#!/usr/bin/python
#
#
opt_dict = {'gsize': '-s',
            'role': '-r',
            'podgroup': '-p',
            'template': '-t',
            'status': '-d',
            'bundle': '-b',
            'patchset': '--patchset',
            'tagsize': '--taggroups',
            'infra': '--infra',
            'gsize': '-s',
            'filter': '-f',
            'regexfilter': '--regexfilter',
            'casetype': '--casetype',
            'dowork': '--dowork',
            'clusteropstat': '--clusteropstat',
            'hostopstat': '--hostopstat',
            'subject': '-g',
            'idb': '--idb',
            'excludes': '--exclude',
            'list_filter': '--HLGrp',
            'impl_plan': '--implplan',
            'host_validation': '--host_validation',
            'auto_close_case': '--auto_close_case',
            'nolinebacker': '--nolinebacker'}

req_sub = ['search(23|43)_prod',
           'search(21|22,41|42)_prod',
           'search(21|22,41|42)_prod',
           'search(23|43)_dr',
           'search(21|22,41|42)_dr',
           'monitor_standby_prod',
           'monitor_primary_prod',
           'monitor_canary_prod',
           'argus_writed_matrics_prod',
           'argus_writed_matrics_canary_prod']
